services:
  streamlit_app:
    build: .
    container_name: simulate_streamlit
    ports:
      - "8501:8501"
    volumes:
      - simulate_data:/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 5s
      timeout: 5s
      retries: 3

  cloudflare_tunnel:
    # Para un rpi en armhf
    image: cloudflare/cloudflared:latest
    container_name: simulate_tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    depends_on:
      streamlit_app:
        condition: service_healthy

volumes:
  simulate_data: